
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Dec  4 2024 01:07:58 CST (Dec  4 2024 07:07:58 UTC)

// Verification Directory fv/Sumador_BK 

module Sumador_BK(a, b, cin, sum, c);
  input [7:0] a, b;
  input cin;
  output [7:0] sum;
  output c;
  wire [7:0] a, b;
  wire cin;
  wire [7:0] sum;
  wire c;
  wire [7:0] carrys;
  wire carrys1, carrys2, carrys3, carrys4, g1, g1_n, g2, g2_n;
  wire g3, g3_2n, g3_n, g4, g4_2n, g4_n, g21_n, n_0;
  wire n_1, p1, p2, p2_n, p3, p3_n, p4, p4_2n;
  wire p4_n, p21_n;
  assign sum[4] = 1'b0;
  assign sum[5] = 1'b0;
  assign sum[6] = 1'b0;
  assign sum[7] = 1'b0;
  Black_Cell_Impar BC3(g3, p3, g2, p2, g3_n, p3_n);
  Estructura_Final EF0(carrys[0], p1, sum[0]);
  Estructura_Final EF1(carrys[1], p2, sum[1]);
  Estructura_Final EF2(carrys[2], p3, sum[2]);
  Estructura_Final EF3(carrys[3], p4, sum[3]);
  HalfAdder EI1(a[0], b[0], g1, p1);
  HalfAdder EI2(a[1], b[1], g2, p2);
  HalfAdder EI3(a[2], b[2], g3, p3);
  HalfAdder EI4(a[3], b[3], g4, p4);
  Gray_Cell_Impar GC1(g1, p1, cin, g1_n);
  Gray_Cell_Impar GC2(g21_n, p21_n, carrys[1], carrys2);
  Gray_Cell_Par GC3(g3_n, p3_n, g1_n, g3_2n);
  Gray_Cell_Impar GC4(g4_2n, p4_2n, carrys[3], carrys4);
  Buffer_Par buffer0(cin, carrys[0]);
  Buffer_Par buffer1(g1_n, carrys1);
  Buffer_Impar buffer1_2(carrys1, carrys[1]);
  Buffer_Impar buffer2(g2, g2_n);
  Buffer_Impar buffer2_2(p2, p2_n);
  Buffer_Impar buffer2_3(g2_n, g21_n);
  Buffer_Impar buffer2_4(p2_n, p21_n);
  Buffer_Impar buffer2_5(carrys2, carrys[2]);
  Buffer_Impar buffer3(g3_2n, carrys3);
  Buffer_Impar buffer3_2(carrys3, carrys[3]);
  Buffer_Impar buffer4(g4, g4_n);
  Buffer_Impar buffer4_2(p4, p4_n);
  Buffer_Impar buffer4_3(g4_n, g4_2n);
  Buffer_Impar buffer4_4(p4_n, p4_2n);
  Buffer_Impar buffer4_5(carrys4, carrys[4]);
  INVX1 g41(.A (n_0), .Y (c));
  AOI21X1 g42__2398(.A (carrys[3]), .B (p3), .C (g3), .Y (n_1));
  BUFX2 drc_bufs(.A (n_1), .Y (n_0));
endmodule

